<a href="https://colab.research.google.com/github/pratyusha124/ML-wine-quality/blob/master/PratyuRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Data Preprocessing

In [1]:
import pandas as pd
import numpy as np


In [2]:
data = pd.read_csv('/content/datasets_4458_8204_winequality-red.csv')

In [3]:
data

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0               7.4             0.700         0.00  ...       0.56      9.4        5
1               7.8             0.880         0.00  ...       0.68      9.8        5
2               7.8             0.760         0.04  ...       0.65      9.8        5
3              11.2             0.280         0.56  ...       0.58      9.8        6
4               7.4             0.700         0.00  ...       0.56      9.4        5
...             ...               ...          ...  ...        ...      ...      ...
1594            6.2             0.600         0.08  ...       0.58     10.5        5
1595            5.9             0.550         0.10  ...       0.76     11.2        6
1596            6.3             0.510         0.13  ...       0.75     11.0        6
1597            5.9             0.645         0.12  ...       0.71     10.2        5
1598            6.0             0.310         0.47  ...       0.66     11.0        6

[1599 rows x 12 columns]

In [4]:
data['quality'].unique()

array([5, 6, 7, 4, 8, 3])

#Separate Features and Target


In [5]:
x = data.iloc[:,:-1].values
y = data.iloc[:, -1].values

In [6]:
x

array([[ 7.4  ,  0.7  ,  0.   , ...,  3.51 ,  0.56 ,  9.4  ],
       [ 7.8  ,  0.88 ,  0.   , ...,  3.2  ,  0.68 ,  9.8  ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  3.26 ,  0.65 ,  9.8  ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  3.42 ,  0.75 , 11.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  3.57 ,  0.71 , 10.2  ],
       [ 6.   ,  0.31 ,  0.47 , ...,  3.39 ,  0.66 , 11.   ]])

In [7]:
y

array([5, 5, 5, ..., 6, 5, 6])

#Splitting of data into test and train 

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [10]:
y_train

array([5, 5, 5, ..., 5, 6, 6])

In [11]:
y_test

array([5, 5, 5, 6, 5, 7, 8, 5, 6, 6, 5, 6, 5, 6, 7, 5, 6, 5, 5, 7, 6, 5,
       5, 6, 5, 5, 6, 6, 5, 6, 5, 6, 5, 5, 6, 6, 7, 7, 5, 6, 6, 3, 7, 6,
       6, 7, 7, 5, 6, 5, 5, 5, 6, 5, 5, 6, 6, 5, 5, 6, 7, 6, 7, 6, 6, 5,
       5, 6, 5, 5, 7, 6, 5, 5, 6, 5, 5, 6, 6, 5, 6, 5, 6, 5, 7, 5, 5, 5,
       6, 6, 5, 8, 5, 7, 5, 5, 6, 5, 7, 5, 6, 6, 7, 6, 6, 5, 5, 5, 5, 6,
       6, 6, 5, 5, 7, 5, 8, 5, 5, 7, 6, 6, 7, 5, 8, 5, 5, 5, 6, 6, 6, 6,
       6, 6, 6, 5, 6, 6, 6, 5, 6, 6, 5, 5, 5, 5, 5, 7, 5, 6, 5, 7, 6, 6,
       5, 5, 5, 7, 7, 5, 6, 5, 5, 7, 6, 5, 5, 5, 6, 7, 5, 5, 6, 5, 3, 6,
       6, 6, 7, 5, 6, 7, 5, 6, 5, 6, 5, 7, 5, 6, 6, 6, 5, 6, 6, 7, 7, 5,
       7, 5, 7, 5, 6, 6, 6, 5, 6, 6, 6, 6, 5, 7, 5, 7, 6, 6, 5, 6, 5, 6,
       6, 6, 6, 5, 6, 5, 5, 6, 5, 6, 6, 6, 6, 5, 5, 7, 7, 5, 6, 5, 7, 7,
       5, 6, 6, 5, 6, 7, 7, 6, 6, 7, 6, 5, 6, 6, 7, 5, 5, 5, 6, 7, 5, 6,
       5, 7, 6, 5, 5, 6, 6, 5, 7, 7, 6, 5, 6, 5, 5, 5, 5, 7, 6, 6, 6, 5,
       5, 5, 5, 7, 5, 5, 6, 6, 5, 5, 4, 6, 5, 5, 7,

#Standardization

In [12]:
from sklearn.preprocessing import StandardScaler

In [13]:
ptrain = y_train.reshape(len(y_train), 1)
ptest = y_test.reshape(len(y_test), 1)

In [14]:
x_sc = StandardScaler()
y_sc = StandardScaler()

In [15]:
xp_train = x_sc.fit_transform(x_train)
yp_train = y_sc.fit_transform(ptrain)

In [16]:
xp_test = x_sc.transform(x_test)
yp_test = y_sc.transform(ptest)

In [17]:
len(xp_train)

1279

In [18]:
xp_train

array([[ 2.11147656, -0.85971832,  1.16162575, ..., -0.98411726,
        -0.28336404, -0.12147429],
       [-0.52003929,  0.93172079, -1.39133565, ...,  1.26652181,
        -0.58062668, -0.9644951 ],
       [ 0.47408892,  1.35158933, -0.24510808, ..., -0.85550931,
        -0.87788932, -0.77715714],
       ...,
       [-0.52003929, -0.01998123, -0.76612062, ..., -0.34107753,
         1.20294915, -1.15183306],
       [-0.3446049 , -1.53150798, -0.03670307, ..., -1.04842123,
         0.78678146,  0.44053959],
       [ 0.00626388, -1.0836482 ,  0.69271447, ...,  0.17335426,
         1.20294915,  0.53420857]])

In [19]:
len(xp_test)

320

In [20]:
xp_test

array([[-0.46156116,  0.65180843, -0.4535131 , ...,  0.43057015,
         0.6678764 , -0.9644951 ],
       [-0.28612677,  0.3159136 , -0.4535131 , ...,  0.75209002,
        -0.4022691 , -0.40248122],
       [ 1.17582648, -1.0836482 ,  1.31792951, ..., -0.85550931,
        -0.10500646, -0.9644951 ],
       ...,
       [ 0.2401764 ,  0.87573832, -1.39133565, ...,  0.30196221,
        -1.23460448, -0.9644951 ],
       [-0.22764864,  0.37189607, -1.07872814, ..., -0.08386163,
        -1.17515195, -0.9644951 ],
       [ 1.87756404, -1.30757809,  1.73473954, ..., -1.30563713,
         1.85692695, -0.30881225]])

In [21]:
yp_train

array([[-0.7662848 ],
       [-0.7662848 ],
       [-0.7662848 ],
       ...,
       [-0.7662848 ],
       [ 0.46962726],
       [ 0.46962726]])

#Train on different algorithms

In [22]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.preprocessing import PolynomialFeatures

In [23]:
r_reg = RandomForestRegressor()
l_reg = LinearRegression()
d_reg = DecisionTreeRegressor()
s_reg = SVR()
p_reg = LinearRegression()

In [24]:
x_pol = PolynomialFeatures(degree=5)
x_pol = x_pol.fit_transform(xp_train)

In [25]:
temp = PolynomialFeatures(degree=5)
temp = temp.fit_transform(xp_test)

In [26]:
r_reg.fit(xp_train, yp_train)
l_reg.fit(xp_train, yp_train)
d_reg.fit(xp_train, yp_train)
s_reg.fit(xp_train, yp_train)
p_reg.fit(x_pol, yp_train)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [27]:
r_pred = r_reg.predict(xp_test)
l_pred = l_reg.predict(xp_test)
d_pred = d_reg.predict(xp_test)
s_pred = s_reg.predict(xp_test)
p_pred = p_reg.predict(temp)

#Result

In [28]:

from sklearn.metrics import r2_score

In [29]:
r = r2_score(yp_test, r_pred)
l = r2_score(yp_test, l_pred)
d = r2_score(yp_test, d_pred)
s = r2_score(yp_test, s_pred)
p = r2_score(yp_test, p_pred)

In [30]:
print(r, l, d, s, p)

0.5738134842519684 0.35644141816227526 0.11417322834645649 0.4590452507814392 -1327.8484268158102


#Conclusion

###We have solved it using regression techique



*   As we have observed RandomForest is giving more efficiency 
    than any other algorithmic techniques
    ,so we can conclude that RandomForest is the best algorithmic       technique for this data set.
